CREATE TABLE cakes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    calories    DECIMAL,
    image       VARCHAR(255),
    price       DECIMAL,
    weight      DECIMAL,
    composition VARCHAR(255),
    shelf_life  VARCHAR(255),
    availability_of_cake INTEGER,
    CONSTRAINT pk_cakes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone VARCHAR(255)                            NOT NULL,
    name  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user"          BIGINT                                  NOT NULL,
    address         VARCHAR(255),
    order_status    INTEGER,
    payment_method  INTEGER,
    delivery_method INTEGER,
    date            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY ("user") REFERENCES users (id);

CREATE TABLE purchases
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cake_id  BIGINT                                  NOT NULL,
    order_id BIGINT                                  NOT NULL,
    count    INTEGER,
    CONSTRAINT pk_purchases PRIMARY KEY (id)
);

ALTER TABLE purchases
    ADD CONSTRAINT FK_PURCHASES_ON_CAKE FOREIGN KEY (cake_id) REFERENCES cakes (id);

ALTER TABLE purchases
    ADD CONSTRAINT FK_PURCHASES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);