openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /cake:
    get:
      description: Returns list of available cakes
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/cakes'


components:
  schemas:
    cakes:
      additionalProperties: false
      type: object
      properties:
        cake_list:
          type: array
          items:
              $ref: '#/components/schemas/cake'

    cake:
      type: object
      description: Cake's short data
      required:
        - name
        - caloties
        - image
        - price
        - weight
      properties:
        id:
          type: integer
          description: id of the cake
        name:
          type: string
          description: Name of the cake
        calories:
          type: number
          description: Calories in cake
        image:
          type: string
          description: Url of cake's image
        price:
          type: number
          description: Price of the cake
        weight:
          type: number
          description: Weight of the cake





